Add h2 dependency.
Test gives following error: 
org.h2.jdbc.JdbcSQLNonTransientException: Method is only allowed for a query. Use execute or executeUpdate instead of executeQuery; SQL statement:
CREATE TABLE CUSTOMER (id number, name varchar(20), age number, address varchar(20), salary number); [90002-199]